[package]
org = "foo"
name = "association"
version = "0.1.0"
distribution = "2201.3.0"

[build-options]
observabilityIncluded = false

[persist.rainier.storage.mysql]
host = "localhost"
port = 3308
user = "root"
password = "Test123#"
database = "rainier_db"

